# Generated by Django 2.0.2 on 2018-02-27 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_type', models.CharField(choices=[('Analog', 'Analog watch'), ('Digital', 'Digital watch'), ('Smart', 'Smart watch')], default='Analog', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
