# Generated by Django 2.0.2 on 2018-02-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('subdivision', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Address_Details',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='aion.Address_Details')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='aion.Address_Details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User_Details',
            },
        ),
    ]
