# Generated by Django 2.0.2 on 2018-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0002_address_details_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
