# Generated by Django 2.0.2 on 2018-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0003_product_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isPurchase',
            field=models.BooleanField(default=False),
        ),
    ]
