# Generated by Django 2.0.2 on 2018-03-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0004_product_ispurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isPurchase',
            new_name='isPurchased',
        ),
    ]
