# Generated by Django 2.0.2 on 2018-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0005_auto_20180303_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='account_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Product Manager', 'Product Manager'), ('Accounting Manager', 'Accounting Manager'), ('Administrator', 'Administrator')], default='Customer', max_length=50),
        ),
    ]
