# Generated by Django 2.0.2 on 2018-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0006_user_details_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_description',
            field=models.TextField(default=''),
        ),
    ]
