# Generated by Django 2.0.2 on 2018-03-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aion', '0007_product_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='address_details',
            name='address_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address_details',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
