# Generated by Django 2.0.2 on 2018-03-12 15:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0009_auto_20180310_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='item_type'),
        ),
    ]
