# Generated by Django 2.0.2 on 2018-03-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aion', '0010_product_item_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('Analog watch', 'Analog watch'), ('Digital watch', 'Digital watch'), ('Smart watch', 'Smart watch')], default='Analog watch', max_length=50),
        ),
    ]
